import { Campaign, Patient, RiskLevel, Screening } from "@/context/AppContext";

const RISK_ORDER: RiskLevel[] = ["Normal", "Mild", "Moderate", "Severe", "Urgent"];

function riskColor(r: RiskLevel): string {
  if (r === "Urgent") return "#dc2626";
  if (r === "Severe") return "#ef4444";
  if (r === "Moderate") return "#f59e0b";
  if (r === "Mild") return "#3b82f6";
  return "#10b981";
}

function riskBg(r: RiskLevel): string {
  if (r === "Urgent") return "#fef2f2";
  if (r === "Severe") return "#fef2f2";
  if (r === "Moderate") return "#fffbeb";
  if (r === "Mild") return "#eff6ff";
  return "#f0fdf4";
}

interface ReportParams {
  campaign: Campaign;
  sessionScreenings: Screening[];
  highRiskScreenings: Screening[];
  patients: Patient[];
  technicianName: string;
  today: string;
}

export function buildSessionReportText(p: ReportParams): string {
  const { campaign, sessionScreenings, highRiskScreenings, patients, technicianName, today } = p;
  const total = sessionScreenings.length;
  const riskCounts: Record<RiskLevel, number> = { Normal: 0, Mild: 0, Moderate: 0, Severe: 0, Urgent: 0 };
  let qualitySum = 0;
  for (const s of sessionScreenings) {
    riskCounts[s.aiRiskLevel] = (riskCounts[s.aiRiskLevel] ?? 0) + 1;
    qualitySum += s.imageQualityScore;
  }
  const avgQuality = total > 0 ? Math.round(qualitySum / total) : 0;
  const highRiskCount = riskCounts.Severe + riskCounts.Urgent;
  const pct = campaign.targetCount > 0
    ? Math.min(100, Math.round((campaign.screenedCount / campaign.targetCount) * 100))
    : 0;

  const riskBreakdown = RISK_ORDER
    .filter((r) => riskCounts[r] > 0)
    .map((r) => `  ${r}: ${riskCounts[r]}`)
    .join("\n");

  const highRiskSection = highRiskScreenings.length > 0
    ? `\n⚠️ HIGH-RISK PATIENTS (${highRiskCount})\n` +
      highRiskScreenings.map((s) => {
        const pat = patients.find((p) => p.id === s.patientId);
        const name = pat ? `${pat.firstName} ${pat.lastName}` : s.patientId;
        return `  • ${name} [${s.aiRiskLevel}] — ${s.aiFindings[0]}`;
      }).join("\n")
    : "";

  return [
    `👁 ERETINA · VisionBridge Session Report`,
    `━━━━━━━━━━━━━━━━━━━━`,
    `📋 Campaign: ${campaign.name}`,
    `📍 District: ${campaign.district} · ${campaign.location}`,
    `🗓 Date: ${today}`,
    `👤 Technician: ${technicianName}`,
    ``,
    `📊 SESSION SUMMARY`,
    `  Screened today: ${total}`,
    `  Avg image quality: ${avgQuality}%`,
    `  High-risk cases: ${highRiskCount}`,
    `  Campaign progress: ${campaign.screenedCount}/${campaign.targetCount} (${pct}%)`,
    ``,
    `🔬 RISK BREAKDOWN`,
    riskBreakdown || `  No screenings recorded`,
    highRiskSection,
    `━━━━━━━━━━━━━━━━━━━━`,
    `Generated by Eretina · VisionBridge`,
    `Confidential — Uganda Data Protection & Privacy Act 2019`,
  ].filter(Boolean).join("\n");
}

export function buildSessionReportHtml(p: ReportParams): string {
  const { campaign, sessionScreenings, highRiskScreenings, patients, technicianName, today } = p;
  const total = sessionScreenings.length;

  const riskCounts: Record<RiskLevel, number> = {
    Normal: 0, Mild: 0, Moderate: 0, Severe: 0, Urgent: 0,
  };
  let qualitySum = 0;
  for (const s of sessionScreenings) {
    riskCounts[s.aiRiskLevel] = (riskCounts[s.aiRiskLevel] ?? 0) + 1;
    qualitySum += s.imageQualityScore;
  }
  const avgQuality = total > 0 ? Math.round(qualitySum / total) : 0;
  const highRiskCount = riskCounts.Severe + riskCounts.Urgent;
  const pct = campaign.targetCount > 0
    ? Math.min(100, Math.round((campaign.screenedCount / campaign.targetCount) * 100))
    : 0;

  const riskRows = RISK_ORDER.map((level) => {
    const count = riskCounts[level];
    const barPct = total > 0 ? Math.round((count / total) * 100) : 0;
    return `
      <tr>
        <td style="padding:8px 12px;font-size:13px;color:#374151;width:90px">${level}</td>
        <td style="padding:8px 12px">
          <div style="background:#e5e7eb;border-radius:4px;height:10px;overflow:hidden">
            <div style="background:${riskColor(level)};width:${barPct}%;height:10px;border-radius:4px"></div>
          </div>
        </td>
        <td style="padding:8px 12px;font-size:13px;font-weight:700;color:${count > 0 ? riskColor(level) : "#9ca3af"};width:40px;text-align:right">${count}</td>
        <td style="padding:8px 12px;font-size:12px;color:#9ca3af;width:50px;text-align:right">${barPct}%</td>
      </tr>`;
  }).join("");

  const highRiskRows = highRiskScreenings.map((s) => {
    const pat = patients.find((p) => p.id === s.patientId);
    const name = pat ? `${pat.firstName} ${pat.lastName}` : s.patientId;
    const pid = pat?.patientId ?? "—";
    const village = pat?.village ?? "—";
    const findings = s.aiFindings.slice(0, 2).join("; ");
    return `
      <tr style="background:${riskBg(s.aiRiskLevel)}">
        <td style="padding:10px 12px;font-size:13px;font-weight:600;color:#111827">${name}</td>
        <td style="padding:10px 12px;font-size:12px;color:#6b7280">${pid}</td>
        <td style="padding:10px 12px;font-size:12px;color:#6b7280">${village}</td>
        <td style="padding:10px 12px">
          <span style="background:${riskBg(s.aiRiskLevel)};color:${riskColor(s.aiRiskLevel)};border:1px solid ${riskColor(s.aiRiskLevel)}40;padding:2px 8px;border-radius:12px;font-size:11px;font-weight:700">${s.aiRiskLevel}</span>
        </td>
        <td style="padding:10px 12px;font-size:12px;color:#374151">${findings}</td>
      </tr>`;
  }).join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Session Report — ${campaign.name}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f9fafb; color: #111827; }
    @media print {
      body { background: white; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div style="max-width:720px;margin:0 auto;padding:32px 24px">

    <!-- Header -->
    <div style="display:flex;align-items:center;gap:16px;margin-bottom:28px;padding-bottom:20px;border-bottom:2px solid #0ea5e9">
      <div style="background:#0ea5e9;width:52px;height:52px;border-radius:14px;display:flex;align-items:center;justify-content:center;flex-shrink:0">
        <span style="color:white;font-size:24px">👁</span>
      </div>
      <div>
        <div style="font-size:11px;font-weight:700;letter-spacing:1px;color:#0ea5e9;text-transform:uppercase">Eretina · VisionBridge</div>
        <div style="font-size:20px;font-weight:700;color:#111827;margin-top:2px">Outreach Session Report</div>
      </div>
      <div style="margin-left:auto;text-align:right">
        <div style="font-size:12px;color:#6b7280">Generated</div>
        <div style="font-size:13px;font-weight:600;color:#374151">${today}</div>
      </div>
    </div>

    <!-- Campaign info -->
    <div style="background:white;border:1px solid #e5e7eb;border-radius:12px;padding:18px;margin-bottom:20px">
      <div style="font-size:11px;font-weight:700;letter-spacing:0.8px;color:#0ea5e9;text-transform:uppercase;margin-bottom:10px">Campaign Details</div>
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">
        <div><span style="font-size:11px;color:#9ca3af">CAMPAIGN</span><br/><span style="font-size:14px;font-weight:600;color:#111827">${campaign.name}</span></div>
        <div><span style="font-size:11px;color:#9ca3af">TYPE</span><br/><span style="font-size:14px;font-weight:600;color:#111827">${campaign.type}</span></div>
        <div><span style="font-size:11px;color:#9ca3af">DISTRICT</span><br/><span style="font-size:14px;font-weight:600;color:#111827">${campaign.district}</span></div>
        <div><span style="font-size:11px;color:#9ca3af">LOCATION</span><br/><span style="font-size:14px;font-weight:600;color:#111827">${campaign.location}</span></div>
        <div><span style="font-size:11px;color:#9ca3af">TECHNICIAN</span><br/><span style="font-size:14px;font-weight:600;color:#111827">${technicianName}</span></div>
        <div><span style="font-size:11px;color:#9ca3af">SESSION DATE</span><br/><span style="font-size:14px;font-weight:600;color:#111827">${today}</span></div>
      </div>
    </div>

    <!-- Stats grid -->
    <div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:12px;margin-bottom:20px">
      ${[
        { label: "Screened Today", value: String(total), color: "#0ea5e9" },
        { label: "Avg Image Quality", value: `${avgQuality}%`, color: "#10b981" },
        { label: "High Risk", value: String(highRiskCount), color: "#ef4444" },
        { label: "Campaign Total", value: `${campaign.screenedCount}/${campaign.targetCount} (${pct}%)`, color: "#8b5cf6" },
      ].map((s) => `
        <div style="background:white;border:1px solid #e5e7eb;border-radius:12px;padding:16px">
          <div style="font-size:22px;font-weight:700;color:${s.color}">${s.value}</div>
          <div style="font-size:11px;color:#9ca3af;margin-top:4px">${s.label}</div>
        </div>`).join("")}
    </div>

    <!-- Risk breakdown -->
    <div style="background:white;border:1px solid #e5e7eb;border-radius:12px;padding:18px;margin-bottom:20px">
      <div style="font-size:11px;font-weight:700;letter-spacing:0.8px;color:#374151;text-transform:uppercase;margin-bottom:14px">Risk Breakdown</div>
      <table style="width:100%;border-collapse:collapse">
        <tbody>${riskRows}</tbody>
      </table>
    </div>

    <!-- High-risk patients -->
    ${highRiskScreenings.length > 0 ? `
    <div style="background:white;border:1px solid #fca5a5;border-radius:12px;padding:18px;margin-bottom:20px">
      <div style="display:flex;align-items:center;gap:8px;margin-bottom:14px">
        <span style="color:#ef4444;font-size:16px">⚠</span>
        <span style="font-size:11px;font-weight:700;letter-spacing:0.8px;color:#ef4444;text-transform:uppercase">High-Risk Patients Requiring Review</span>
      </div>
      <table style="width:100%;border-collapse:collapse;font-size:13px">
        <thead>
          <tr style="border-bottom:1px solid #e5e7eb">
            <th style="padding:8px 12px;text-align:left;font-size:11px;color:#9ca3af;font-weight:600">NAME</th>
            <th style="padding:8px 12px;text-align:left;font-size:11px;color:#9ca3af;font-weight:600">ID</th>
            <th style="padding:8px 12px;text-align:left;font-size:11px;color:#9ca3af;font-weight:600">VILLAGE</th>
            <th style="padding:8px 12px;text-align:left;font-size:11px;color:#9ca3af;font-weight:600">RISK</th>
            <th style="padding:8px 12px;text-align:left;font-size:11px;color:#9ca3af;font-weight:600">AI FINDINGS</th>
          </tr>
        </thead>
        <tbody>${highRiskRows}</tbody>
      </table>
    </div>` : ""}

    <!-- Footer -->
    <div style="text-align:center;padding-top:24px;border-top:1px solid #e5e7eb;margin-top:8px">
      <div style="font-size:12px;color:#9ca3af">Generated by Eretina · VisionBridge TeleOphthalmology Platform · Uganda</div>
      <div style="font-size:11px;color:#d1d5db;margin-top:4px">This report is confidential. Handle in accordance with Uganda Data Protection &amp; Privacy Act 2019.</div>
    </div>

  </div>
</body>
</html>`;
}
